# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.10.0

pipelines:
  branches:
    master:
    - step:
        caches:
        - node
        script: # Modify the commands below to build your repository.
        - yarn install --frozen-lockfile
        - yarn run test
        - yarn run build

  pull-requests:
    master:
    - step:
        caches:
        - node
        script: # Modify the commands below to build your repository.
        - yarn install --frozen-lockfile
        - yarn run test
        - yarn run build